---
# settings for the flowdock-notification-resource pipeline
meta:
  target: sw
  url:    https://ci.vsphere.starkandwayne.com
  name:   flowdock-notification

  initial_version: 0.0.1

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  dockerhub:
    email:    (( vault "secret/dockerhub:email" ))
    username: (( vault "secret/dockerhub:username" ))
    password: (( vault "secret/dockerhub:password" ))
    repository: starkandwayne/flowdock-notification-resource

  github:
    owner: starkandwayne
    repo:  flowdock-notification-resource
    private_key:  (( vault "secret/pipelines/flowdock-notification-resource/github:private" ))
    access_token: (( vault "secret/pipelines/flowdock-notification-resource/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/flowdock-notification-resource/slack:webhook" ))
    channel: '#botspam'

